INSERT INTO star (name, galacticLongitude, galacticLatitude, starClass, discoverer) VALUES ('star_0', '01', '02', 'Blue', 'discoverer_0');
INSERT INTO star (name, galacticLongitude, galacticLatitude, starClass, discoverer) VALUES ('star_1', '11', '12', 'White-blue', 'discoverer_1');
INSERT INTO star (name, galacticLongitude, galacticLatitude, starClass, discoverer) VALUES ('star_2', '21', '22', 'White', 'discoverer_2');
INSERT INTO star (name, galacticLongitude, galacticLatitude, starClass, discoverer) VALUES ('star_3', '31', '32', 'Yellow-white', 'discoverer_3');
INSERT INTO star (name, galacticLongitude, galacticLatitude, starClass, discoverer) VALUES ('star_4', '41', '42', 'Yellow', 'discoverer_4');
INSERT INTO star (name, galacticLongitude, galacticLatitude, starClass, discoverer) VALUES ('star_5', '51', '52', 'Orange', 'discoverer_5');
INSERT INTO star (name, galacticLongitude, galacticLatitude, starClass, discoverer) VALUES ('star_6', '61', '62', 'Red', 'discoverer_6');
INSERT INTO star (name, galacticLongitude, galacticLatitude, starClass, discoverer) VALUES ('star_7', '71', '72', 'Red', 'discoverer_7');
INSERT INTO star (name, galacticLongitude, galacticLatitude, starClass, discoverer) VALUES ('star_8', '81', '82', 'Red', 'discoverer_8');
INSERT INTO star (name, galacticLongitude, galacticLatitude, starClass, discoverer) VALUES ('star_9', '91', '92', 'Yellow', 'discoverer_9');
INSERT INTO star (name, galacticLongitude, galacticLatitude, starClass, discoverer) VALUES ('star_10', '101', '102', 'Orange', 'discoverer_10');
INSERT INTO star (name, galacticLongitude, galacticLatitude, starClass, discoverer) VALUES ('star_11', '111', '112', 'Yellow', 'discoverer_11');
INSERT INTO star (name, galacticLongitude, galacticLatitude, starClass, discoverer) VALUES ('star_12', '121', '122', 'White', 'discoverer_12');
INSERT INTO star (name, galacticLongitude, galacticLatitude, starClass, discoverer) VALUES ('star_13', '131', '132', 'Blue', 'discoverer_13');
INSERT INTO star (name, galacticLongitude, galacticLatitude, starClass, discoverer) VALUES ('star_14', '141', '142', 'White', 'discoverer_14');
INSERT INTO star (name, galacticLongitude, galacticLatitude, starClass, discoverer) VALUES ('star_15', '151', '152', 'Blue', 'discoverer_15');
INSERT INTO star (name, galacticLongitude, galacticLatitude, starClass, discoverer) VALUES ('star_16', '161', '162', 'Orange', 'discoverer_16');
INSERT INTO star_discoverer (name) VALUES ('discoverer_0');
INSERT INTO star_discoverer (name) VALUES ('discoverer_1');
INSERT INTO star_discoverer (name) VALUES ('discoverer_2');
INSERT INTO star_discoverer (name) VALUES ('discoverer_3');
INSERT INTO star_discoverer (name) VALUES ('discoverer_4');
INSERT INTO star_discoverer (name) VALUES ('discoverer_5');
INSERT INTO star_discoverer (name) VALUES ('discoverer_6');
INSERT INTO star_discoverer (name) VALUES ('discoverer_7');
INSERT INTO star_discoverer (name) VALUES ('discoverer_8');
INSERT INTO star_discoverer (name) VALUES ('discoverer_9');
INSERT INTO star_discoverer (name) VALUES ('discoverer_10');
INSERT INTO star_discoverer (name) VALUES ('discoverer_11');
INSERT INTO star_discoverer (name) VALUES ('discoverer_12');
INSERT INTO star_discoverer (name) VALUES ('discoverer_13');
INSERT INTO star_discoverer (name) VALUES ('discoverer_14');
INSERT INTO star_discoverer (name) VALUES ('discoverer_15');
INSERT INTO star_discoverer (name) VALUES ('discoverer_16');